In [7]:
import torch
import numpy as np
import pandas as pd


In [8]:
torch.__version__

'1.11.0'

In [9]:
data = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [10]:
x = torch.tensor(data,dtype=torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
arr = np.ones((3, 3))
torch.tensor(arr)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
# torch.tensor(arr, device='cuda')

In [17]:
# numpy arr和tensor共享内存 一改并改
t = torch.from_numpy(arr)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [18]:
t[1,1] = 9
t

tensor([[1., 1., 1.],
        [1., 9., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
out_t = torch.tensor([1])
# 这里制定了 out
t = torch.zeros((3, 3), out=out_t)
print(t, '\n', out_t)
# id 是取内存地址。最终 t 和 out_t 是同一个内存地址
print(id(t), id(out_t), id(t) == id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
5451558640 5451558640 True


In [23]:
t = torch.full((3, 3), 10)
t

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

In [24]:
t = torch.arange(2, 10, 2)
t

tensor([2, 4, 6, 8])

In [26]:
# 线性
t = torch.linspace(2, 10, 6)
t

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])

In [29]:
# log函数型
t = torch.logspace(2, 10, 6)
t

tensor([1.0000e+02, 3.9811e+03, 1.5849e+05, 6.3096e+06, 2.5119e+08, 1.0000e+10])

In [33]:
# 对角矩阵
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
# 生成正态分布 (高斯分布)
# mean：均值 std: 标准差
# mean：张量 std: 标量
# 这里需要设置 size
t_normal = torch.normal(mean=0., std=1., size=(4,2))
t_normal

tensor([[ 0.0721,  0.1394],
        [ 0.8149,  0.3006],
        [ 2.3974,  0.1924],
        [-0.2983,  0.6207]])

In [38]:
mean = torch.arange(1, 5, dtype=torch.float)
mean

tensor([1., 2., 3., 4.])